### ISSUE TITLE
Taalcode staat per ongeluk binnen lexicale expressie

### ISSUE THREAD

**Issue by wouterbeek** [cultureelerfgoed/CEO#4]
In het label van de eigenschap `ceo:hoofdadres` staat de taalcode per ongeluk in de lexicale expressie:
```turtle
"Hoofdadres @nl"
```

Dit moet waarschijnlijk zijn:
```turtle
"Hoofdadres"@nl
```

Zie [deze regel](https://github.com/cultureelerfgoed/CEO/blob/master/CEO_v1.26.ttl#L1370)

**Comment by jolietjakeblues** [comment]
Dank voor de opmerking. Hoofdadres komt vanaf versie 1.27 niet meer voor in de ceo.
