### ISSUE TITLE
Domein van 'ceo:heeftPeriode'

### ISSUE THREAD

**Issue by wouterbeek** [cultureelerfgoed/CEO#8]
Op [deze regel](https://github.com/cultureelerfgoed/CEO/blob/master/CEO_v1.31.ttl#L922) staat mogelijk een verkeerd domein: `ceo:heeftEindDatering` is een eigenschap; bij een domein wordt een klasse verwacht.

```turtle
ceo:heeftPeriode
  rdfs:domain ceo:BeginDatering, ceo:heeftEindDatering ;
```

**Comment by wouterbeek** [comment]
Dit lijkt sterk op de eerder gerapporteerde #5

**Comment by jolietjakeblues** [comment]
Wouter, volgens mij is deze inmiddels gecorrigeerd in versie 1.31.
ceo:heeftPeriode
  rdf:type owl:ObjectProperty ;
  dcterms:created "2018-04-10"^^xsd:date ;
  dcterms:modified "2022-04-28"^^xsd:date ;
  rdfs:comment "De property heeftPeriode legt de relatie tussen de datering en de periode vast. "@nl ;
  rdfs:domain ceo:BeginDatering, ceo:EindDatering ;
  rdfs:label "Heeft periode"@nl ;
  rdfs:range skos:Concept ;
